version: '3'

tasks:
  docker:
    desc: Build speechtotext docker image and publish to gchr.io
    cmds:
      - go mod tidy
      - DOCKER_BUILDKIT=1 docker buildx build --ssh=default --platform linux/amd64,linux/arm64 -t ghcr.io/func-it/speech-to-text:latest .

  docker-push:
    desc: Build speechtotext docker image and publish to gchr.io
    cmds:
      - task: docker
      - docker push ghcr.io/func-it/speech-to-text:latest

  upgrade:
    cmds:
      - task: docker-push
      - task: staging:upgrade

includes:
  staging:
    taskfile: ./Taskfile.staging.yml
    dir: .
