version: '3'

tasks:
  build:
    desc: Build the speech to text binary
    cmds:
      - go build --ldflags '-extldflags "-static" -w -s' -mod=readonly -o ./speech-to-text -tags netgo .

  docker:
    desc: Build speechtotext docker image and publish to gchr.io
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/func-it/speech-to-text:latest .

