version: '3'

dotenv: [ '.config/default.env' ]

env:
  PROTOBUF_PATH: proto
  PROTOBUF_PATH_GENERATED: gen/service
  DOCKER_REGISTRY: funcit
  DOCKER_IMAGE: speechtotext
  DOCKER_TAG: latest

tasks:
  proto:
    cmds:
      - protoc -I${PROTOBUF_PATH} --go_out=${PROTOBUF_PATH_GENERATED} --go-grpc_out=require_unimplemented_servers=false:${PROTOBUF_PATH_GENERATED} ${PROTOBUF_PATH}/*.proto
      - protoc-go-inject-tag -input="${PROTOBUF_PATH_GENERATED}/*.pb.go"

  mod:
    cmds:
      - go get ./...
      - go mod tidy

  build:
    cmds:
      - task: proto
      - task: mod

  build-docker:
    cmds:
      - docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG} .

  services-up:
    cmds:
      - docker compose
        -f infra/docker-compose.yml
        --env-file .config/default.env
        up speechToText